langugage: node_js
node_js:
  - "12"
install: skip
os: linux
before_script:
  - npm i -g npm@6.12.0
  - npm install
script:
  - npm test
notifications:
  email:
    recipients:
      - chandan@technogise.com
      - aamir@technogise.com
      - satyam@technogise.com
      - shubhamsahu@technogise.com
    on_success: change
    on_failure: always
